### PR TITLE
docs: update readme with information on gene-normalizer ddb data

### LINKED ISSUE #71: Get gene normalizer data
I don't have any of the files that were used in gene ddb prod instance. I think I'll have to re-run so we can store the files used.

### PR DESCRIPTION
**Pull request by korikuzma**
close #71

### CODE REVIEW

**Review by wesleygoar — DISMISSED** [review]

**Comment by korikuzma** [comment]
@wesleygoar I'm going to convert this to a draft. A VRS ID changed for CIViC.

```
-2747   CCND3 Amplification     protein False   Not provided    ga4gh:CX.snGEICIn_4wNAikMj_UUXrWz-JZaIMAj       normalize
+2747   CCND3 Amplification     protein False   Not provided    ga4gh:CX.CIClUxP0kJhNTWO---DxvolwslfxSoqv       normalize
```

The gene ddb instance on aws is pointing to 2022 data, but this PR has the latest data as of today.

**Comment by korikuzma** [comment]
> @wesleygoar I'm going to convert this to a draft. A VRS ID changed for CIViC.
> 
> ```
> -2747   CCND3 Amplification     protein False   Not provided    ga4gh:CX.snGEICIn_4wNAikMj_UUXrWz-JZaIMAj       normalize
> +2747   CCND3 Amplification     protein False   Not provided    ga4gh:CX.CIClUxP0kJhNTWO---DxvolwslfxSoqv       normalize
> ```
> 
> The gene ddb instance on aws is pointing to 2022 data, but this PR has the latest data as of today.

The Sequence Location end value changed from `42048894` to `42050035` in `ncbi_locations`.

**Comment by korikuzma** [comment]
@wesleygoar Is this a big deal? I'm going to have @jarbesfeld re-run genie

**Comment by wesleygoar** [comment]
@korikuzma do we have amplification variants in any of the other datasets we normalize?

**Comment by korikuzma** [comment]
> @korikuzma do we have amplification variants in any of the other datasets we normalize?

@wesleygoar MOA, but none changed

**Comment by korikuzma** [comment]
I'm mainly having @jarbesfeld re-run so that we can confirm the lockfile requirements work for all. I think everyone has different deps atm.

**Comment by wesleygoar** [comment]
Cool lets do it. @jarbesfeld let it rip.

**Comment by korikuzma** [comment]
@wesleygoar can I go ahead and merge this PR?

**Comment by wesleygoar** [comment]
@korikuzma Make it So

**Pull request merged**
